language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

# use operating systems.
os:
  - linux
  - osx

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget --no-cookies --no-check-certificate --header \"Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-macosx-x64.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil mount jdk-8u66-macosx-x64.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo installer -pkg /Volumes/JDK\ 8\ Update\ 66/JDK\ 8\ Update\ 66.pkg -target LocalSystem; fi

#before_install:
#  - "export DISPLAY=:99.0"
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
