language: java

jdk: oraclejdk8

addons:
  apt:
    packages: oracle-java8-installer

# Operating system
os: linux

# sudo required
sudo: required

matrix:
  include:
    - env: TOKEN=nogui
      script: mvn clean -Dtest=!gui/*Test.java,!RunTestOnly.java install
    - env: TOKEN=gui
      script: mvn clean -Dtest=!commandline/*Test.java,!implementationchecker/*Test.java install
  exclude:
    - jdk: oraclejdk8

before_install:
  - if [ "${TOKEN}" != "nogui" ]; then export DISPLAY=:99.0; fi
  - if [ "${TOKEN}" != "nogui" ]; then sh -e /etc/init.d/xvfb start; fi

#before_install:
#  - "export DISPLAY=:99.0"
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
