language: java

jdk: oraclejdk8

addons:
  apt:
    packages: oracle-java8-installer

os: linux
sudo: required

matrix:
  include:
    # Custom builds
    - env: TOKEN=nogui
      script: mvn test -B -Dtest=commandline/*Test.java,implementationchecker/*Test.java
    - env: TOKEN=gui
      script: mvn test -B -Dtest=gui/*Test.java
  exclude:
    # Exclude default build
    - jdk: oraclejdk8

before_install:
  - if [ "${TOKEN}" != "nogui" ]; then export DISPLAY=:99.0; fi
  - if [ "${TOKEN}" != "nogui" ]; then sh -e /etc/init.d/xvfb start; fi