language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

# use operating systems.
os:
  - linux

matrix:
    include:
        - os: linux
          jdk: oraclejdk8
          env: TOKEN=gui
          sudo: required

before_install:
  - if [ "${TOKEN}" == "gui" ]; then echo "GUI"; fi
  - if [ "${TOKEN}" != "gui" ]; then echo "NOGUI"; fi
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

#before_install:
#  - "export DISPLAY=:99.0"
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
